CREATE TABLE group5.company_location (
	location_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	location CHAR(2) NOT NULL UNIQUE
);

INSERT INTO group5.company_location (location) VALUES ('ES');
INSERT INTO group5.company_location (location) VALUES ('US');
INSERT INTO group5.company_location (location) VALUES ('CA');
INSERT INTO group5.company_location (location) VALUES ('DE');
INSERT INTO group5.company_location (location) VALUES ('GB');
INSERT INTO group5.company_location (location) VALUES ('NG');
INSERT INTO group5.company_location (location) VALUES ('IN');
INSERT INTO group5.company_location (location) VALUES ('HK');
INSERT INTO group5.company_location (location) VALUES ('NL');
INSERT INTO group5.company_location (location) VALUES ('CH');
INSERT INTO group5.company_location (location) VALUES ('CF');
INSERT INTO group5.company_location (location) VALUES ('FR');
INSERT INTO group5.company_location (location) VALUES ('FI');
INSERT INTO group5.company_location (location) VALUES ('UA');
INSERT INTO group5.company_location (location) VALUES ('IE');
INSERT INTO group5.company_location (location) VALUES ('IL');
INSERT INTO group5.company_location (location) VALUES ('GH');
INSERT INTO group5.company_location (location) VALUES ('CO');
INSERT INTO group5.company_location (location) VALUES ('SG');
INSERT INTO group5.company_location (location) VALUES ('AU');
INSERT INTO group5.company_location (location) VALUES ('SE');
INSERT INTO group5.company_location (location) VALUES ('SI');
INSERT INTO group5.company_location (location) VALUES ('MX');
INSERT INTO group5.company_location (location) VALUES ('BR');
INSERT INTO group5.company_location (location) VALUES ('PT');
INSERT INTO group5.company_location (location) VALUES ('RU');
INSERT INTO group5.company_location (location) VALUES ('TH');
INSERT INTO group5.company_location (location) VALUES ('HR');
INSERT INTO group5.company_location (location) VALUES ('VN');
INSERT INTO group5.company_location (location) VALUES ('EE');
INSERT INTO group5.company_location (location) VALUES ('AM');
INSERT INTO group5.company_location (location) VALUES ('BA');
INSERT INTO group5.company_location (location) VALUES ('KE');
INSERT INTO group5.company_location (location) VALUES ('GR');
INSERT INTO group5.company_location (location) VALUES ('MK');
INSERT INTO group5.company_location (location) VALUES ('LV');
INSERT INTO group5.company_location (location) VALUES ('RO');
INSERT INTO group5.company_location (location) VALUES ('PK');
INSERT INTO group5.company_location (location) VALUES ('IT');
INSERT INTO group5.company_location (location) VALUES ('MA');
INSERT INTO group5.company_location (location) VALUES ('PL');
INSERT INTO group5.company_location (location) VALUES ('AL');
INSERT INTO group5.company_location (location) VALUES ('AR');
INSERT INTO group5.company_location (location) VALUES ('LT');
INSERT INTO group5.company_location (location) VALUES ('AS');
INSERT INTO group5.company_location (location) VALUES ('CR');
INSERT INTO group5.company_location (location) VALUES ('IR');
INSERT INTO group5.company_location (location) VALUES ('BS');
INSERT INTO group5.company_location (location) VALUES ('HU');
INSERT INTO group5.company_location (location) VALUES ('AT');
INSERT INTO group5.company_location (location) VALUES ('SK');
INSERT INTO group5.company_location (location) VALUES ('CZ');
INSERT INTO group5.company_location (location) VALUES ('TR');
INSERT INTO group5.company_location (location) VALUES ('PR');
INSERT INTO group5.company_location (location) VALUES ('DK');
INSERT INTO group5.company_location (location) VALUES ('BO');
INSERT INTO group5.company_location (location) VALUES ('PH');
INSERT INTO group5.company_location (location) VALUES ('BE');
INSERT INTO group5.company_location (location) VALUES ('ID');
INSERT INTO group5.company_location (location) VALUES ('EG');
INSERT INTO group5.company_location (location) VALUES ('AE');
INSERT INTO group5.company_location (location) VALUES ('LU');
INSERT INTO group5.company_location (location) VALUES ('MY');
INSERT INTO group5.company_location (location) VALUES ('HN');
INSERT INTO group5.company_location (location) VALUES ('JP');
INSERT INTO group5.company_location (location) VALUES ('DZ');
INSERT INTO group5.company_location (location) VALUES ('IQ');
INSERT INTO group5.company_location (location) VALUES ('CN');
INSERT INTO group5.company_location (location) VALUES ('NZ');
INSERT INTO group5.company_location (location) VALUES ('CL');
INSERT INTO group5.company_location (location) VALUES ('MD');
INSERT INTO group5.company_location (location) VALUES ('MT');

ALTER TABLE group5.main ADD COLUMN location_id INT;

UPDATE group5.main
SET location_id = company_location.location_id
FROM group5.company_location
WHERE group5.main.company_location = group5.company_location.location;

ALTER TABLE group5.main DROP COLUMN company_location;

ALTER TABLE group5.main
ADD CONSTRAINT location_fk_listing
FOREIGN KEY (location_id)
REFERENCES group5.company_location (location_id)
ON DELETE CASCADE;

