CREATE TABLE group5.company_size (
	size_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	size CHAR(1) NOT NULL UNIQUE
);

INSERT INTO group5.company_size (size) VALUES ('S'), ('M'), ('L');

ALTER TABLE group5.main ADD COLUMN size_id INT;

UPDATE group5.main
SET size_id = company_size.size_id
FROM group5.company_size
WHERE group5.main.company_size = group5.company_size.size;

ALTER TABLE group5.main DROP COLUMN company_size;

ALTER TABLE group5.main
ADD CONSTRAINT size_fk_listing
FOREIGN KEY (size_id)
REFERENCES group5.company_size (size_id)
ON DELETE CASCADE;

