CREATE TABLE group5.experience (
		experience_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		experience CHAR(2) NOT NULL UNIQUE
);

INSERT INTO group5.experience (experience)
VALUES ('SE'), ('MI'), ('EN'), ('EX');

ALTER TABLE group5.main ADD COLUMN experience_id INT;

UPDATE group5.main
SET experience_id = experience.experience_id
FROM group5.experience
WHERE group5.main.experience = group5.experience.experience;

ALTER TABLE group5.main DROP COLUMN experience;

ALTER TABLE group5.main
ADD CONSTRAINT experience_fk_listing
FOREIGN KEY (experience_id)
REFERENCES group5.experience (experience_id)
ON DELETE CASCADE;

