CREATE TABLE group5.job_title (
	title_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO group5.job_title(title) VALUES('Principal Data Scientist');
INSERT INTO group5.job_title(title) VALUES('ML Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Scientist');
INSERT INTO group5.job_title(title) VALUES('Applied Scientist');
INSERT INTO group5.job_title(title) VALUES('Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Data Modeler');
INSERT INTO group5.job_title(title) VALUES('Research Engineer');
INSERT INTO group5.job_title(title) VALUES('Analytics Engineer');
INSERT INTO group5.job_title(title) VALUES('Business Intelligence Engineer');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Strategist');
INSERT INTO group5.job_title(title) VALUES('Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Computer Vision Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Quality Analyst');
INSERT INTO group5.job_title(title) VALUES('Compliance Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Data Architect');
INSERT INTO group5.job_title(title) VALUES('Applied Machine Learning Engineer');
INSERT INTO group5.job_title(title) VALUES('AI Developer');
INSERT INTO group5.job_title(title) VALUES('Research Scientist');
INSERT INTO group5.job_title(title) VALUES('Data Analytics Manager');
INSERT INTO group5.job_title(title) VALUES('Business Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Applied Data Scientist');
INSERT INTO group5.job_title(title) VALUES('Staff Data Analyst');
INSERT INTO group5.job_title(title) VALUES('ETL Engineer');
INSERT INTO group5.job_title(title) VALUES('Data DevOps Engineer');
INSERT INTO group5.job_title(title) VALUES('Head of Data');
INSERT INTO group5.job_title(title) VALUES('Data Science Manager');
INSERT INTO group5.job_title(title) VALUES('Data Manager');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Researcher');
INSERT INTO group5.job_title(title) VALUES('Big Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Specialist');
INSERT INTO group5.job_title(title) VALUES('Lead Data Analyst');
INSERT INTO group5.job_title(title) VALUES('BI Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Director of Data Science');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Scientist');
INSERT INTO group5.job_title(title) VALUES('MLOps Engineer');
INSERT INTO group5.job_title(title) VALUES('AI Scientist');
INSERT INTO group5.job_title(title) VALUES('Autonomous Vehicle Technician');
INSERT INTO group5.job_title(title) VALUES('Applied Machine Learning Scientist');
INSERT INTO group5.job_title(title) VALUES('Lead Data Scientist');
INSERT INTO group5.job_title(title) VALUES('Cloud Database Engineer');
INSERT INTO group5.job_title(title) VALUES('Financial Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Data Infrastructure Engineer');
INSERT INTO group5.job_title(title) VALUES('Software Data Engineer');
INSERT INTO group5.job_title(title) VALUES('AI Programmer');
INSERT INTO group5.job_title(title) VALUES('Data Operations Engineer');
INSERT INTO group5.job_title(title) VALUES('BI Developer');
INSERT INTO group5.job_title(title) VALUES('Data Science Lead');
INSERT INTO group5.job_title(title) VALUES('Deep Learning Researcher');
INSERT INTO group5.job_title(title) VALUES('BI Analyst');
INSERT INTO group5.job_title(title) VALUES('Data Science Consultant');
INSERT INTO group5.job_title(title) VALUES('Data Analytics Specialist');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Infrastructure Engineer');
INSERT INTO group5.job_title(title) VALUES('BI Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Head of Data Science');
INSERT INTO group5.job_title(title) VALUES('Insight Analyst');
INSERT INTO group5.job_title(title) VALUES('Deep Learning Engineer');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Software Engineer');
INSERT INTO group5.job_title(title) VALUES('Big Data Architect');
INSERT INTO group5.job_title(title) VALUES('Product Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Computer Vision Software Engineer');
INSERT INTO group5.job_title(title) VALUES('Azure Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Marketing Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Analytics Lead');
INSERT INTO group5.job_title(title) VALUES('Data Lead');
INSERT INTO group5.job_title(title) VALUES('Data Science Engineer');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Research Engineer');
INSERT INTO group5.job_title(title) VALUES('NLP Engineer');
INSERT INTO group5.job_title(title) VALUES('Manager Data Management');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Developer');
INSERT INTO group5.job_title(title) VALUES('3D Computer Vision Researcher');
INSERT INTO group5.job_title(title) VALUES('Principal Machine Learning Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Analytics Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Analytics Consultant');
INSERT INTO group5.job_title(title) VALUES('Data Management Specialist');
INSERT INTO group5.job_title(title) VALUES('Data Science Tech Lead');
INSERT INTO group5.job_title(title) VALUES('Data Scientist Lead');
INSERT INTO group5.job_title(title) VALUES('Cloud Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Data Operations Analyst');
INSERT INTO group5.job_title(title) VALUES('Marketing Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Power BI Developer');
INSERT INTO group5.job_title(title) VALUES('Product Data Scientist');
INSERT INTO group5.job_title(title) VALUES('Principal Data Architect');
INSERT INTO group5.job_title(title) VALUES('Machine Learning Manager');
INSERT INTO group5.job_title(title) VALUES('Lead Machine Learning Engineer');
INSERT INTO group5.job_title(title) VALUES('ETL Developer');
INSERT INTO group5.job_title(title) VALUES('Cloud Data Architect');
INSERT INTO group5.job_title(title) VALUES('Lead Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Head of Machine Learning');
INSERT INTO group5.job_title(title) VALUES('Principal Data Analyst');
INSERT INTO group5.job_title(title) VALUES('Principal Data Engineer');
INSERT INTO group5.job_title(title) VALUES('Staff Data Scientist');
INSERT INTO group5.job_title(title) VALUES('Finance Data Analyst');

ALTER TABLE group5.main ADD COLUMN title_id INT;

UPDATE group5.main
SET title_id = job_title.title_id
FROM group5.job_title
WHERE group5.main.job_title = group5.job_title.title;

ALTER TABLE group5.main DROP COLUMN job_title;

ALTER TABLE group5.main
ADD CONSTRAINT job_title_fk_listing
FOREIGN KEY (title_id)
REFERENCES group5.job_title (title_id)
ON DELETE CASCADE;


