CREATE TABLE group5.remote_ratio (
	remote_ratio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	remote_ratio INT NOT NULL UNIQUE
);

INSERT INTO group5.remote_ratio (remote_ratio) VALUES (0), (50), (100);

ALTER TABLE group5.main ADD COLUMN remote_ratio_id INT;

UPDATE group5.main
SET remote_ratio_id = remote_ratio.remote_ratio_id
FROM group5.remote_ratio
WHERE group5.main.remote_ratio = group5.remote_ratio.remote_ratio;

ALTER TABLE group5.main DROP COLUMN remote_ratio;

ALTER TABLE group5.main
ADD CONSTRAINT remote_ratio_fk_listing
FOREIGN KEY (remote_ratio_id)
REFERENCES group5.remote_ratio (remote_ratio_id)
ON DELETE CASCADE;

