CREATE TABLE group5.work_year (
		work_year_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		work_year INT NOT NULL UNIQUE
);

INSERT INTO group5.work_year (work_year) VALUES (2023), (2022), (2021), (2020);

ALTER TABLE group5.main ADD COLUMN work_year_id INT;

UPDATE group5.main
SET work_year_id = work_year.work_year_id
FROM group5.work_year
WHERE group5.main.work_year = group5.work_year.work_year;

ALTER TABLE group5.main DROP COLUMN work_year;

ALTER TABLE group5.main
ADD CONSTRAINT work_year_fk_listing
FOREIGN KEY (work_year_id)
REFERENCES group5.work_year (work_year_id)
ON DELETE CASCADE;

